name             'lita'
maintainer       'Harlan Barnes'
maintainer_email 'hbarnes@pobox.com'
license          'Apache 2.0'
description      'Installs/configures the Lita chatbot'
long_description 'Installs/configures the Lita chatbot'
version          '1.0.1'

supports 'ubuntu'

depends 'runit'
depends 'apt'
depends 'build-essential'
depends 'rvm', '~> 0.9.4'
depends 'yum-epel', '~> 0.3.6'